name: tidy_town
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  flutter_tts: ^3.8.5
  audioplayers: ^5.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome.gif
    
    - assets/images/avatar.png
    - assets/images/home_back.png
    - assets/images/1.png
    - assets/images/recycle/recycle_ws.jpeg
    - assets/images/recycle/paper.png
    - assets/images/recycle/plastic.png
    - assets/images/recycle/glass.png
    - assets/images/recycle/metal.png
    - assets/images/recycle/pizza.jpg
    - assets/images/recycle/banana.jpeg
    - assets/images/recycle/background.jpeg
    - assets/images/recycle/story1.jpeg
    - assets/images/recycle/story2.png
    - assets/images/recycle/story3.png
    - assets/images/recycle/story4.png
    - assets/images/compost/compost_ws.png
    - assets/images/landfill/landfill_ws.jpg
    - assets/images/recycle/lunalast.gif
    - assets/images/recycle/luna3.png
    - assets/images/recycle/luna1.png
    - assets/images/recycle/luna2.png
    - assets/images/recycle/luna4.png
    - assets/images/recycle/luna5.png
    
    - assets/images/recycle/wally1.png
    - assets/images/recycle/wally2.png
    - assets/images/recycle/wally3.png
    - assets/images/recycle/wally4.png
    - assets/images/recycle/wally5.png
    - assets/images/recycle/wally6.png
    - assets/images/recycle/wally7.png
    - assets/images/recycle/wally8.png
    - assets/images/recycle/moral.png
    - assets/images/HomePage.png
    - assets/images/recycle/learning.png



  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700